apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.containerImage }}:{{ .Values.imageVersion }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            {{- range .Values.containerEnvVars }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
          livenessProbe:
            initialDelaySeconds: 5
            grpc:
              port: {{ .Values.containerPort }}
            periodSeconds: 5
          readinessProbe:
            initialDelaySeconds: 5
            grpc:
              port: {{ .Values.containerPort }}
            periodSeconds: 5

